PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS "user" (
	"uid"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"telegram"	TEXT,
	"email"	TEXT,
	"nick"	TEXT NOT NULL DEFAULT '',
	"remarks"	TEXT NOT NULL DEFAULT '',
	UNIQUE("telegram"),
	UNIQUE("email")
);

CREATE TABLE IF NOT EXISTS "register" (
	"uid"	INTEGER NOT NULL,
	"legal_id"	BLOB NOT NULL,
	"registered"	INTEGER NOT NULL DEFAULT (UNIXEPOCH()),
	"confirmed"	INTEGER NOT NULL DEFAULT 0,
	"arrived"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("uid"),
	FOREIGN KEY("uid") REFERENCES "user"("uid") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "volunteer" (
	"uid"	INTEGER NOT NULL,
	"arrive"	TEXT NOT NULL,
	"depart"	TEXT NOT NULL,
	"contrib"	TEXT NOT NULL,
	"tshirt"	TEXT NOT NULL,
	"other"	TEXT NOT NULL,
	"status"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("uid"),
	FOREIGN KEY("uid") REFERENCES "register"("uid") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "badge" (
	"uid"	INTEGER NOT NULL,
	"line1"	TEXT NOT NULL DEFAULT '',
	"line2"	TEXT NOT NULL DEFAULT '',
	PRIMARY KEY("uid"),
	FOREIGN KEY("uid") REFERENCES "register"("uid") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "pgp_info" (
	"uid"	INTEGER NOT NULL,
	"fpr"	TEXT NOT NULL,
	"keyuid"	TEXT NOT NULL,
	PRIMARY KEY("uid"),
	FOREIGN KEY("uid") REFERENCES "register"("uid") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "pgp_sign" (
	"signer"	INTEGER NOT NULL,
	"signee"	INTEGER NOT NULL,
	"level"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("signer","signee"),
	FOREIGN KEY("signee") REFERENCES "pgp_info"("uid") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("signer") REFERENCES "register"("uid") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "notify" (
	"nid"	INTEGER NOT NULL,
	"uid"	INTEGER NOT NULL,
	"title"	TEXT NOT NULL,
	"content"	TEXT NOT NULL,
	"lock"	TEXT,
	"retry"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("nid"),
	FOREIGN KEY("uid") REFERENCES "user"("uid") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "vote_info" (
	"vid"	INTEGER NOT NULL,
	"title"	TEXT NOT NULL,
	"ended"	INTEGER NOT NULL DEFAULT 0,
	"favor"	INTEGER,
	"against"	INTEGER,
	"abstain"	INTEGER,
	PRIMARY KEY("vid")
);

CREATE TABLE IF NOT EXISTS "vote_detail" (
	"vid"	INTEGER NOT NULL,
	"uid"	INTEGER NOT NULL,
	"vote"	INTEGER NOT NULL,
	PRIMARY KEY("vid","uid"),
	FOREIGN KEY("uid") REFERENCES "register"("uid") ON UPDATE CASCADE,
	FOREIGN KEY("vid") REFERENCES "vote_info"("vid") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "draw_info" (
	"did"	INTEGER NOT NULL,
	"title"	TEXT NOT NULL,
	"count"	INTEGER NOT NULL DEFAULT 1,
	"ended"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("did")
);

CREATE TABLE IF NOT EXISTS "draw_detail" (
	"did"	INTEGER NOT NULL,
	"uid"	INTEGER NOT NULL,
	"color"	TEXT NOT NULL,
	"win"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("did","uid"),
	FOREIGN KEY("did") REFERENCES "draw_info"("did") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("uid") REFERENCES "register"("uid") ON UPDATE CASCADE
);

COMMIT;
